import "@/styles/globals.scss";
import "@/styles/variables.scss";
import "@/styles/mixins.scss";

import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Socials from "@/components/Socials";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Socials />
        {children}
        <Footer />
      </body>
    </html>
  );
}
