name: Push

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Run NPM format
        run: npm run format:check

      - name: Run NPM lint
        run: npm run lint
